FMA | Javascript Client | Library Structure
capitalone/federated-model-aggregation pull request #36
Opened 2023-07-21 20:57 UTC by openrijal

- directory structure and base files for javascript client library
- directory structure for example javascript project folder

2023-07-25 04:06 UTC, JGSweets commented on examples/client_examples/javascript_client/README.md
> +bash run_example.sh 3 abc123 average_layers http://host.docker.internal:8000 http://0.0.0.0:8080
Let's update `abc123` to be `<user_id>`

2023-07-25 17:00 UTC, ksneab7 commented on clients/javascript_client/fma_connect/clients.ts
> +const defaultSettings = new DefaultSettings()
Ensure that the files end with proper spacing

2023-08-01 03:54 UTC, JGSweets commented
@ksneab7 @taylorfturner bump for review

2023-08-01 14:59 UTC, taylorfturner requested changes
Looking good -- some new line at EOF and verbiage. Otherwise, looking good

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/fma_connect/settings.ts
> +}
new line EOF

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/jest.config.js
> +  };
new line EOF

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/package.json
> +}
new line EOF

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/tsconfig.json
> +}
new line EOF

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/package.json
> +
same

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/utils.ts
> +}
same

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/README.md
> +Please run the ```setup``` at the top level of the directory
```suggestion
Please run the the following command at the top level of the repo
```
currently which directory is ambiguous...  is it the `clients/` or `javascript_client` or entire repo?

2023-08-01 14:59 UTC, taylorfturner commented on clients/javascript_client/README.md
> +```npm test```
any particular location this needs to be run?

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +Quickstart --
```suggestion
Quickstart
```

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +Quickstart --
not sure the `--` is needed

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +2. EXAMPLE
```suggestion
2. Example Run
```

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +1. Install requirements
```suggestion
1. Install  
```

2023-08-01 14:59 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +3. Run Client.ts
```suggestion
3. Run Client (`client.ts`)
```

2023-08-01 18:37 UTC, taylorfturner requested changes

2023-08-01 18:37 UTC, taylorfturner commented on clients/javascript_client/jest.config.js
> +
you may have some unneeded white space here

2023-08-01 18:37 UTC, taylorfturner commented on examples/client_examples/javascript_client/utils.ts
> +}
new line EOF

2023-08-01 18:37 UTC, taylorfturner commented on clients/javascript_client/README.md
> +[README.md](examples/browser_client/README.md)
this appears to be a non-existent path...

2023-08-01 18:48 UTC, taylorfturner requested changes

2023-08-01 18:48 UTC, taylorfturner commented on clients/javascript_client/README.md
> +Please run `npm setup` at `clients/javascript_client` directory
```suggestion
Run `npm setup` in `clients/javascript_client` directory
```

2023-08-01 18:48 UTC, taylorfturner commented on clients/javascript_client/README.md
> +[README.md](examples/client_examples/javascript_client/README.md)
maybe render the other README here... so the user doesn't have to open another window

2023-08-02 13:33 UTC, taylorfturner commented on clients/javascript_client/README.md
> +[README.md](examples/client_examples/javascript_client/README.md)
ah I see

2023-08-02 13:34 UTC, taylorfturner commented on examples/client_examples/javascript_client/README.md
> +2. Example Run
```suggestion
2. Run Example
```
re-word to match the `bash` script that is actually run

2023-08-02 16:08 UTC, taylorfturner requested changes

2023-08-02 16:10 UTC, taylorfturner approved these changes
LGTM

2023-08-03 12:43 UTC, taylorfturner commented
bump @tyfarnan @micdavis

2023-08-03 17:07 UTC, merged