Dependency security vuln fix
capitalone/federated-model-aggregation pull request #51
Opened 2023-12-12 14:07 UTC by micdavis

### Changes

- Bumped `Django` version
- forcing transitive dependency to safe version

2023-12-12 14:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/capitalone/federated-model-aggregation?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/capitalone/federated-model-aggregation?pullRequest=51) before we can accept your contribution.<br/><hr/>**Michael** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/capitalone/federated-model-aggregation?pullRequest=51) it.</sub>

2023-12-12 14:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/capitalone/federated-model-aggregation?pullRequest=51) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/capitalone/federated-model-aggregation?pullRequest=51) before we can accept your contribution.<br/><hr/>**Michael** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/capitalone/federated-model-aggregation?pullRequest=51) it.</sub>

2023-12-12 18:04 UTC, taylorfturner approved these changes

2023-12-18 13:48 UTC, taylorfturner requested changes
Blocking

2023-12-18 16:08 UTC, tyfarnan approved these changes

2023-12-19 16:10 UTC, taylorfturner approved these changes
LGTM

2023-12-19 16:11 UTC, merged